ci: impl draft workflow2

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,11 +6,20 @@ on:
       release_version:
         description: 'Release version'
         required: true
-
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
+
 jobs:
+    validate-version-input:
+        runs-on: ubuntu-latest
+        steps:
+            - run: |
+                VERSION=${{ github.event.inputs.release_version  }}
+                if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+$ ]]; then
+                echo "Invalid version format: $VERSION"
+                exit 1
+                fi
     build:
         runs-on: ubuntu-latest
 
@@ -32,7 +41,7 @@ jobs:
           uses: actions/upload-artifact@v3
           with:
             name: dist-files
-            path: dist/*.whl
+            path: dist/*
     
     release:
         name: release
